name: master_thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=h8cf3c4a_0
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py39h02fc5c5_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aom=3.5.0=h7ea286d_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - autoreject=0.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=openblas
  - blinker=1.5=pyhd8ed1ab_0
  - bottleneck=1.3.5=py39h4d8bf0d_1
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py39h02fc5c5_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.12.7=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.2.0=pyhd8ed1ab_0
  - cairo=1.16.0=h73a0509_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.6=py39haaf3ac1_0
  - cryptography=39.0.0=py39haa0b8cc_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py39h0ef5a74_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=5.1.2=gpl_hf318d42_106
  - flatbuffers=2.0.8=hb7217d7_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39h02fc5c5_1
  - freetype=2.12.1=hd633e50_1
  - frozenlist=1.3.3=py39h02fc5c5_0
  - future=0.18.3=pyhd8ed1ab_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h27ca646_2
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - google-auth=2.15.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=h9f76cd9_1001
  - grpc-cpp=1.47.1=h503f348_7
  - grpcio=1.47.1=py39h13431ec_7
  - h5io=0.1.7=pyh8a188c0_0
  - h5py=3.7.0=nompi_py39hc9149d8_102
  - harfbuzz=6.0.0=hddbc195_0
  - hdf5=1.12.2=nompi_h55deafc_101
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - imbalanced-learn=0.10.1=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - ipykernel=6.15.2=pyh736e0ef_0
  - ipython=8.7.0=pyhd1c38e8_0
  - jasper=2.0.33=hba35424_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.1=pyhd8ed1ab_0
  - jpeg=9e=he4db4b2_2
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39h2804cbe_1
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39haaf3ac1_1
  - krb5=1.20.1=h127bd45_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.14=h481adae_1
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libaec=1.0.6=hb7217d7_1
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.87.0=hbe9bab4_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_27
  - libgfortran5=11.3.0=hdaf2cc0_27
  - libglib=2.74.1=h4646484_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - libjpeg-turbo=2.1.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.51.0=hd184df1_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.7.0=py39hcd7568c_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=hb80f160_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.0=heb92581_0
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.6=h7cfbb63_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h02fc5c5_2
  - matplotlib-base=3.6.2=py39h35e9e80_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - multidict=6.0.4=py39h02fc5c5_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h63371fa_1
  - numexpr=2.8.4=py39h79ee842_0
  - numpy=1.23.5=py39h1398885_0
  - numpy-base=1.23.5=py39h90707a3_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencv=4.7.0=py39hdf13c20_0
  - openh264=2.3.1=hb7217d7_1
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=1.1.1s=h03a7124_1
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=h29577a5_0
  - packaging=22.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h8bbe137_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - plotly=5.9.0=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=4.21.12=py39h23fbdae_0
  - psutil=5.9.0=py39hb18efdd_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.7.0=py39h85045c0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h2d96c93_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=22.12.6=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=23.2.0=py39h8faa4b9_0
  - re2=2022.06.01=h9a09cb3_1
  - readline=8.2=h1a28f6b_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.1.3=py39h57c6424_1
  - scipy=1.10.0=py39h18313fe_0
  - seaborn=0.12.1=hd8ed1ab_0
  - seaborn-base=0.12.1=pyhd8ed1ab_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h17c5cce_2
  - sqlite=3.40.0=h2229b38_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py39h7b9fbcb_0
  - svt-av1=1.4.1=h7ea286d_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - tensorboard=2.10.0=pyhd8ed1ab_2
  - tensorboard-data-server=0.6.1=py39haa0b8cc_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=cpu_py39h2839aeb_0
  - tensorflow-base=2.10.0=cpu_py39h0d4f425_0
  - tensorflow-estimator=2.10.0=cpu_py39h63f9d84_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tk=8.6.12=he1e0b03_0
  - tornado=6.2=py39h02fc5c5_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.7.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - uncertainties=3.1.7=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py39h02fc5c5_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py39h02fc5c5_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.8=h80987f9_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.2=py39h02fc5c5_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=hf913c23_6
  - pip:
      - beautifulsoup4==4.11.2
      - bs4==0.0.1
      - cloudpickle==2.2.1
      - colorlog==6.7.0
      - coverage==5.5
      - dask==2023.1.1
      - distributed==2023.1.1
      - easydev==0.12.0
      - fsspec==2023.1.0
      - heapdict==1.0.1
      - locket==1.0.0
      - mat73==0.60
      - mne==1.3.1
      - moabb==0.4.6
      - modin==0.18.1
      - msgpack==1.0.4
      - numpyencoder==0.3.0
      - pandas==1.5.3
      - partd==1.3.0
      - pyeer==0.5.6
      - pyriemann==0.3
      - pyyaml==5.4.1
      - sortedcontainers==2.4.0
      - soupsieve==2.4
      - spectrum==0.8.1
      - tblib==1.7.0
      - tensorflow-addons==0.19.0
      - toolz==0.12.0
      - typeguard==3.0.2
      - zict==2.2.0

